### ISSUE TITLE
Page doesn't scroll to correct location when opened with some hash tags

### ISSUE THREAD

**Issue by jesperfj** [heroku/office#8]
When you open the page with a hash tag, e.g. http://office.heroku.com/#326 it doesn't always focus on the selected room. For example, for room 326, the page opens at the bottom with the room itself out of view.

This is a regression that was introduced with https://github.com/heroku/office/pull/7

**Comment by caseywatts** [comment]
since our move to the Landmark building, this site is behind us now lol
closing this issue
